"""Initialisation des tables SQLModel

Revision ID: 8a708d201a29
Revises: 
Create Date: 2026-09-02 20:42:43.826972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a708d201a29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lexicon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phonetic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('syllables', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lexicon_phonetic'), 'lexicon', ['phonetic'], unique=False)
    op.create_index(op.f('ix_lexicon_word'), 'lexicon', ['word'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=False)
    op.create_table('rhymevault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phonetic_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('words_combo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rhymevault_phonetic_pattern'), 'rhymevault', ['phonetic_pattern'], unique=False)
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version')
    op.drop_index(op.f('ix_rhymevault_phonetic_pattern'), table_name='rhymevault')
    op.drop_table('rhymevault')
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_lexicon_word'), table_name='lexicon')
    op.drop_index(op.f('ix_lexicon_phonetic'), table_name='lexicon')
    op.drop_table('lexicon')
    # ### end Alembic commands ###
